### ISSUE TITLE
ActiveRecord::PendingMigrationErrorというエラーメッセージが出ますが解決できません

### ISSUE THREAD

**Issue by Masaki-Maejima** [Masaki-Maejima/task_app#2]
## ActiveRecord::PendingMigrationErrorというエラーメッセージが出ますが解決できません。
自分で調べてみたのは、マイグレーションファイルを一旦削除して再びマイグレートする手順を試してみましたが、解決できず、マイグレーションファイルが現在どのような状態か把握できなくなってしまいわからない状況です。

>Migrations are pending. To resolve this issue, run: bin/rails db:migrate RAILS_ENV=development

このエラーが出るまでに実行した手順は以下の通りです。
```
$ rails  db:migrateしたが応答なし
```
↓

```
$ rails db:resetを実行したのち、Udemyを参考にしたものは削除した
```
↓
```
$ rails g migration AddColumnToTask
```
↓
作成したファイルにカラムおよびデータ型を追加
```rb
class AddColumnToTask < ActiveRecord::Migration[5.2]
  def change
    add_column :tasks, :title, :string
    add_column :tasks, :content, :text
  end
end
```
↓
```
再び$ rails db:migrate
```
↓
 ```
== 20181211021333 AddColumnToTask: migrating ==================================
-- add_column(:tasks, :title, :string)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: duplicate column name: title: ALTER TABLE "tasks" ADD "title" varchar
/Users/masaki/task_app/db/migrate/20181211021333_add_column_to_task.rb:3:in `change'
/Users/masaki/task_app/bin/rails:9:in `<top (required)>'
/Users/masaki/task_app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: duplicate column name: title: ALTER TABLE "tasks" ADD "title" varchar
/Users/masaki/task_app/db/migrate/20181211021333_add_column_to_task.rb:3:in `change'
/Users/masaki/task_app/bin/rails:9:in `<top (required)>'
/Users/masaki/task_app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
SQLite3::SQLException: duplicate column name: title
/Users/masaki/task_app/db/migrate/20181211021333_add_column_to_task.rb:3:in `change'
/Users/masaki/task_app/bin/rails:9:in `<top (required)>'
/Users/masaki/task_app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
適応されたと思っていたが適応されていなかったようで、ここから再び
```
rails db:migrate reset
rails db:migrate
```
の手順を踏んだが解決できず進めない状況です。

## 気になる点
>development.sqlite３のファイルが点滅していないので、sqlite3が適応されていない。
text.sqlite3も同様

## 追記　ステータスコマンドの実行
```
$ rails db:migrate:status

database: /Users/masaki/task_app/db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20181206051200  Create tasks
   up     20181211021333  ********** NO FILE **********
  down    20181211040344  Add column to task
```

**Comment by NerdyBoyCool** [comment]
> マイグレーションファイルを一旦削除して

こちらなぜ、削除したのですか？？？

**Comment by NerdyBoyCool** [comment]
マイグレーションファイルは消してしまうと、予期せぬ不具合が出るので削除しないでください。

**Comment by NerdyBoyCool** [comment]
取りいそぎ

以下の作業をするときは、rails serverを止めてください
``rails db:drop``
``rails db:create``
``rails db:migrate``
としてみてください

**Comment by Masaki-Maejima** [comment]
わかりました。
